sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-math
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-math.git
    - secure: "dr2AQGskqc4IaJb1jtPDcw9UxXwZU0SemdcErG3OJY70l2zxYrwu6i0SShUjpXPafywo6mK7rwV9UYXBzr2PgO6UerNKUkWcYFb0Rj6KIzNZhrTPAZi7kBd/y1mjAn9QVmT2l4H1Boe3Xi18NvHT4M9pwdz06AqR7IVrVb2oQKX7cEFbP+3Yy0++O74n4CMgp7EjR4PLiYUoDIJMYHwIzDjGwp6VXLSvW1u7BFFnWNTiifDXZPLyInlUwiqNMY9XGDWxubKdFsBM2ZqXuyQO0KxLXnCP/wZi+WBpDNkyv8NIu4qei0z9k0SPl5VBCiei3TIzZBTeSGuaxCY82mUc8Vv96QnMjQDcUca9g22rJeh5Wd18KZqzPPpst6tdipMjrXBVtskItZqT5XMzfuIM0+40Lx95GTcSWXAZKIC5wO/2wjYgk+NKDHJrfuKw4ZEXhVZStVnZlnRYgLUkRjVpRavZYvGo5juriVEJl/RwhqojwrfoKuaIFVnPzMQdx9w9PhKw8GfEM0dgt1Lij1vELA09fcVKKR/JeiRxMOGx+oKeDkFUKQvrcE35eJouc2LQUzPkgKkCY2JA/C3qEYXnQlhYYaLgcjA3Ecrnkq/HBcsrS2/nYeoEjiiqVF/kfaIBxawUDzGjjM1r8mKneMy5LtZ+5MxPFHtPyWkzoDUSjZc="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi
